directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_MEAN:asn#6.itm.2 REGISTER_NAME LOOP_MEAN:asn#6.itm.2
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/ac_math::ac_sqrt_pwl<AC_TRN,22,17,AC_TRN,AC_WRAP,14,8,AC_TRN,AC_WRAP>:ac_math::ac_sqrt_pwl<AC_TRN,22,17,AC_TRN,AC_WRAP,14,8,AC_TRN,AC_WRAP>:or.itm.2 REGISTER_NAME LOOP_MEAN:asn#6.itm.2
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_MEAN:asn#3.itm.1 REGISTER_NAME LOOP_MEAN:asn#3.itm.1
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_OUT:asn#1.itm.1 REGISTER_NAME LOOP_MEAN:asn#3.itm.1
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_MEAN.stage_0 REGISTER_NAME LOOP_MEAN.stage_0
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_OUT.stage_0.10 REGISTER_NAME LOOP_MEAN.stage_0
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_VAR:slc()(13)#1.itm REGISTER_NAME LOOP_MEAN.stage_0
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/exit:LOOP_VAR.sva REGISTER_NAME LOOP_MEAN.stage_0
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_CH:i#1.sva REGISTER_NAME LOOP_CH:i#1.sva
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_CH:i#2.sva REGISTER_NAME LOOP_CH:i#1.sva
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_CH:i.sva REGISTER_NAME LOOP_CH:i#1.sva
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_MEAN.stage_0.2 REGISTER_NAME LOOP_MEAN.stage_0.2
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_OUT.stage_0.2 REGISTER_NAME LOOP_MEAN.stage_0.2
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_MEAN.stage_0.3 REGISTER_NAME LOOP_MEAN.stage_0.3
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_OUT.stage_0.3 REGISTER_NAME LOOP_MEAN.stage_0.3
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_VAR:acc#4.cse.sva REGISTER_NAME LOOP_VAR:acc#4.cse.sva
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_CH:idx(14:0).sva.1 REGISTER_NAME LOOP_VAR:acc#4.cse.sva
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_CH:mean_tmp(19:8).sva REGISTER_NAME LOOP_VAR:acc#4.cse.sva
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_CH:mean_tmp(19:8).sva.dfm REGISTER_NAME LOOP_VAR:acc#4.cse.sva
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/ac_math::ac_sqrt_pwl<AC_TRN,22,17,AC_TRN,AC_WRAP,14,8,AC_TRN,AC_WRAP>:ac_math::ac_sqrt_pwl<AC_TRN,22,17,AC_TRN,AC_WRAP,14,8,AC_TRN,AC_WRAP>:or.itm.3 REGISTER_NAME ac_math::ac_sqrt_pwl<AC_TRN,22,17,AC_TRN,AC_WRAP,14,8,AC_TRN,AC_WRAP>:ac_math::ac_sqrt_pwl<AC_TRN,22,17,AC_TRN,AC_WRAP,14,8,AC_TRN,AC_WRAP>:or.itm.3
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/exit:LOOP_MEAN.sva.2 REGISTER_NAME ac_math::ac_sqrt_pwl<AC_TRN,22,17,AC_TRN,AC_WRAP,14,8,AC_TRN,AC_WRAP>:ac_math::ac_sqrt_pwl<AC_TRN,22,17,AC_TRN,AC_WRAP,14,8,AC_TRN,AC_WRAP>:or.itm.3
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/LOOP_OUT.stage_0.4 REGISTER_NAME LOOP_OUT.stage_0.4
directive set /UNET_IP::batchnorm_relu/UNET_IP::batchnorm_relu:run_batch/run_batch/exit:LOOP_MEAN.sva.st.1 REGISTER_NAME LOOP_OUT.stage_0.4
