directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/for:c.sva REGISTER_NAME for:c.sva
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/in_c.sva REGISTER_NAME for:c.sva
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/for:for:for:mul#1.itm.1 REGISTER_NAME for:for:for:mul#1.itm.1
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/out_c.sva REGISTER_NAME for:for:for:mul#1.itm.1
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_Y:asn#16.itm.3 REGISTER_NAME LOOP_Y:asn#16.itm.3
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/for:for:for.stage_0.3 REGISTER_NAME LOOP_Y:asn#16.itm.3
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_Y:acc#14.itm.1 REGISTER_NAME LOOP_Y:acc#14.itm.1
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/for:for:for:w.sva REGISTER_NAME LOOP_Y:acc#14.itm.1
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_Y.stage_0 REGISTER_NAME LOOP_Y.stage_0
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/exit:for:for:for.sva.st.1 REGISTER_NAME LOOP_Y.stage_0
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_Y.stage_0.2 REGISTER_NAME LOOP_Y.stage_0.2
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/exit:for:for:for.sva.st.2 REGISTER_NAME LOOP_Y.stage_0.2
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_Y.stage_0.3 REGISTER_NAME LOOP_Y.stage_0.3
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/for:for:for.stage_0 REGISTER_NAME LOOP_Y.stage_0.3
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_Y.stage_0.4 REGISTER_NAME LOOP_Y.stage_0.4
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/for:for:for.stage_0.2 REGISTER_NAME LOOP_Y.stage_0.4
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_Y:mul#3.itm.1 REGISTER_NAME LOOP_Y:mul#3.itm.1
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/for:for:for:asn#9.itm.2 REGISTER_NAME LOOP_Y:mul#3.itm.1
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_Y:mul#5.itm.2 REGISTER_NAME LOOP_Y:mul#5.itm.2
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/for:for:for:asn#9.itm.1 REGISTER_NAME LOOP_Y:mul#5.itm.2
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/j.sva#1 REGISTER_NAME LOOP_Y:mul#5.itm.2
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_WIDTH:mul#1.itm REGISTER_NAME LOOP_WIDTH:mul#1.itm
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/for:for:h.sva REGISTER_NAME LOOP_WIDTH:mul#1.itm
directive set /UNET_IP::conv2d/UNET_IP::conv2d:run_conv/run_conv/LOOP_Y:asn#20.itm.1 REGISTER_NAME LOOP_WIDTH:mul#1.itm
