// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.1/1091966 Production Release
//  HLS Date:       Wed Feb 14 09:07:18 PST 2024
// 
//  Generated by:   m111061631@ws41
//  Generated date: Fri Jun  7 09:35:28 2024
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    EdgeDetect_IP_EdgeDetect_Top
// ------------------------------------------------------------------


module EdgeDetect_IP_EdgeDetect_Top (
  clk, rst, arst_n, dat_in_rsc_dat, dat_in_rsc_vld, dat_in_rsc_rdy, widthIn, heightIn,
      dat_out_rsc_dat, dat_out_rsc_vld, dat_out_rsc_rdy, ctrl_denoise_rsc_dat, ctrl_denoise_triosy_lz,
      ctrl_edgedect_rsc_dat, ctrl_edgedect_triosy_lz, line_buf0_rsc_Denoise_inst_en,
      line_buf0_rsc_Denoise_inst_q, line_buf0_rsc_Denoise_inst_we, line_buf0_rsc_Denoise_inst_d,
      line_buf0_rsc_Denoise_inst_adr, line_buf1_rsc_Denoise_inst_en, line_buf1_rsc_Denoise_inst_q,
      line_buf1_rsc_Denoise_inst_we, line_buf1_rsc_Denoise_inst_d, line_buf1_rsc_Denoise_inst_adr,
      line_buf0_rsc_EdgeDetect_Filter_inst_en, line_buf0_rsc_EdgeDetect_Filter_inst_q,
      line_buf0_rsc_EdgeDetect_Filter_inst_we, line_buf0_rsc_EdgeDetect_Filter_inst_d,
      line_buf0_rsc_EdgeDetect_Filter_inst_adr, line_buf1_rsc_EdgeDetect_Filter_inst_en,
      line_buf1_rsc_EdgeDetect_Filter_inst_q, line_buf1_rsc_EdgeDetect_Filter_inst_we,
      line_buf1_rsc_EdgeDetect_Filter_inst_d, line_buf1_rsc_EdgeDetect_Filter_inst_adr
);
  input clk;
  input rst;
  input arst_n;
  input [7:0] dat_in_rsc_dat;
  input dat_in_rsc_vld;
  output dat_in_rsc_rdy;
  input [10:0] widthIn;
  input [9:0] heightIn;
  output [7:0] dat_out_rsc_dat;
  output dat_out_rsc_vld;
  input dat_out_rsc_rdy;
  input [1:0] ctrl_denoise_rsc_dat;
  output ctrl_denoise_triosy_lz;
  input [1:0] ctrl_edgedect_rsc_dat;
  output ctrl_edgedect_triosy_lz;
  output line_buf0_rsc_Denoise_inst_en;
  input [15:0] line_buf0_rsc_Denoise_inst_q;
  output line_buf0_rsc_Denoise_inst_we;
  output [15:0] line_buf0_rsc_Denoise_inst_d;
  output [9:0] line_buf0_rsc_Denoise_inst_adr;
  output line_buf1_rsc_Denoise_inst_en;
  input [15:0] line_buf1_rsc_Denoise_inst_q;
  output line_buf1_rsc_Denoise_inst_we;
  output [15:0] line_buf1_rsc_Denoise_inst_d;
  output [9:0] line_buf1_rsc_Denoise_inst_adr;
  output line_buf0_rsc_EdgeDetect_Filter_inst_en;
  input [15:0] line_buf0_rsc_EdgeDetect_Filter_inst_q;
  output line_buf0_rsc_EdgeDetect_Filter_inst_we;
  output [15:0] line_buf0_rsc_EdgeDetect_Filter_inst_d;
  output [9:0] line_buf0_rsc_EdgeDetect_Filter_inst_adr;
  output line_buf1_rsc_EdgeDetect_Filter_inst_en;
  input [15:0] line_buf1_rsc_EdgeDetect_Filter_inst_q;
  output line_buf1_rsc_EdgeDetect_Filter_inst_we;
  output [15:0] line_buf1_rsc_EdgeDetect_Filter_inst_d;
  output [9:0] line_buf1_rsc_EdgeDetect_Filter_inst_adr;


  // Interconnect Declarations
  wire [7:0] dat_out_rsc_dat_n_Denoise_inst;
  wire line_buf0_rsc_en_n_Denoise_inst;
  wire [15:0] line_buf0_rsc_d_n_Denoise_inst;
  wire [9:0] line_buf0_rsc_adr_n_Denoise_inst;
  wire line_buf1_rsc_en_n_Denoise_inst;
  wire [15:0] line_buf1_rsc_d_n_Denoise_inst;
  wire [9:0] line_buf1_rsc_adr_n_Denoise_inst;
  wire [7:0] dat_out_rsc_dat_n_EdgeDetect_Filter_inst;
  wire line_buf0_rsc_en_n_EdgeDetect_Filter_inst;
  wire [15:0] line_buf0_rsc_d_n_EdgeDetect_Filter_inst;
  wire [9:0] line_buf0_rsc_adr_n_EdgeDetect_Filter_inst;
  wire line_buf1_rsc_en_n_EdgeDetect_Filter_inst;
  wire [15:0] line_buf1_rsc_d_n_EdgeDetect_Filter_inst;
  wire [9:0] line_buf1_rsc_adr_n_EdgeDetect_Filter_inst;
  wire dat_in_rsc_rdy_n_Denoise_inst_bud;
  wire dat_out_rsc_vld_n_Denoise_inst_bud;
  wire dat_in_rsc_rdy_n_EdgeDetect_Filter_inst_bud;
  wire ctrl_signal_triosy_lz_n_Denoise_inst_bud;
  wire line_buf0_rsc_we_n_Denoise_inst_bud;
  wire line_buf1_rsc_we_n_Denoise_inst_bud;
  wire dat_out_rsc_vld_n_EdgeDetect_Filter_inst_bud;
  wire ctrl_signal_triosy_lz_n_EdgeDetect_Filter_inst_bud;
  wire line_buf0_rsc_we_n_EdgeDetect_Filter_inst_bud;
  wire line_buf1_rsc_we_n_EdgeDetect_Filter_inst_bud;


  // Interconnect Declarations for Component Instantiations 
  EdgeDetect_IP_Denoise_IP Denoise_inst (
      .clk(clk),
      .rst(rst),
      .arst_n(arst_n),
      .dat_in_rsc_dat(dat_in_rsc_dat),
      .dat_in_rsc_vld(dat_in_rsc_vld),
      .dat_in_rsc_rdy(dat_in_rsc_rdy_n_Denoise_inst_bud),
      .widthIn(widthIn),
      .heightIn(heightIn),
      .dat_out_rsc_dat(dat_out_rsc_dat_n_Denoise_inst),
      .dat_out_rsc_vld(dat_out_rsc_vld_n_Denoise_inst_bud),
      .dat_out_rsc_rdy(dat_in_rsc_rdy_n_EdgeDetect_Filter_inst_bud),
      .ctrl_signal_rsc_dat(ctrl_denoise_rsc_dat),
      .ctrl_signal_triosy_lz(ctrl_signal_triosy_lz_n_Denoise_inst_bud),
      .line_buf0_rsc_en(line_buf0_rsc_en_n_Denoise_inst),
      .line_buf0_rsc_q(line_buf0_rsc_Denoise_inst_q),
      .line_buf0_rsc_we(line_buf0_rsc_we_n_Denoise_inst_bud),
      .line_buf0_rsc_d(line_buf0_rsc_d_n_Denoise_inst),
      .line_buf0_rsc_adr(line_buf0_rsc_adr_n_Denoise_inst),
      .line_buf1_rsc_en(line_buf1_rsc_en_n_Denoise_inst),
      .line_buf1_rsc_q(line_buf1_rsc_Denoise_inst_q),
      .line_buf1_rsc_we(line_buf1_rsc_we_n_Denoise_inst_bud),
      .line_buf1_rsc_d(line_buf1_rsc_d_n_Denoise_inst),
      .line_buf1_rsc_adr(line_buf1_rsc_adr_n_Denoise_inst)
    );
  EdgeDetect_IP_EdgeDetect_Filter EdgeDetect_Filter_inst (
      .clk(clk),
      .rst(rst),
      .arst_n(arst_n),
      .dat_in_rsc_dat(dat_out_rsc_dat_n_Denoise_inst),
      .dat_in_rsc_vld(dat_out_rsc_vld_n_Denoise_inst_bud),
      .dat_in_rsc_rdy(dat_in_rsc_rdy_n_EdgeDetect_Filter_inst_bud),
      .widthIn(widthIn),
      .heightIn(heightIn),
      .dat_out_rsc_dat(dat_out_rsc_dat_n_EdgeDetect_Filter_inst),
      .dat_out_rsc_vld(dat_out_rsc_vld_n_EdgeDetect_Filter_inst_bud),
      .dat_out_rsc_rdy(dat_out_rsc_rdy),
      .ctrl_signal_rsc_dat(ctrl_edgedect_rsc_dat),
      .ctrl_signal_triosy_lz(ctrl_signal_triosy_lz_n_EdgeDetect_Filter_inst_bud),
      .line_buf0_rsc_en(line_buf0_rsc_en_n_EdgeDetect_Filter_inst),
      .line_buf0_rsc_q(line_buf0_rsc_EdgeDetect_Filter_inst_q),
      .line_buf0_rsc_we(line_buf0_rsc_we_n_EdgeDetect_Filter_inst_bud),
      .line_buf0_rsc_d(line_buf0_rsc_d_n_EdgeDetect_Filter_inst),
      .line_buf0_rsc_adr(line_buf0_rsc_adr_n_EdgeDetect_Filter_inst),
      .line_buf1_rsc_en(line_buf1_rsc_en_n_EdgeDetect_Filter_inst),
      .line_buf1_rsc_q(line_buf1_rsc_EdgeDetect_Filter_inst_q),
      .line_buf1_rsc_we(line_buf1_rsc_we_n_EdgeDetect_Filter_inst_bud),
      .line_buf1_rsc_d(line_buf1_rsc_d_n_EdgeDetect_Filter_inst),
      .line_buf1_rsc_adr(line_buf1_rsc_adr_n_EdgeDetect_Filter_inst)
    );
  assign dat_in_rsc_rdy = dat_in_rsc_rdy_n_Denoise_inst_bud;
  assign ctrl_denoise_triosy_lz = ctrl_signal_triosy_lz_n_Denoise_inst_bud;
  assign line_buf0_rsc_Denoise_inst_en = line_buf0_rsc_en_n_Denoise_inst;
  assign line_buf0_rsc_Denoise_inst_we = line_buf0_rsc_we_n_Denoise_inst_bud;
  assign line_buf0_rsc_Denoise_inst_d = line_buf0_rsc_d_n_Denoise_inst;
  assign line_buf0_rsc_Denoise_inst_adr = line_buf0_rsc_adr_n_Denoise_inst;
  assign line_buf1_rsc_Denoise_inst_en = line_buf1_rsc_en_n_Denoise_inst;
  assign line_buf1_rsc_Denoise_inst_we = line_buf1_rsc_we_n_Denoise_inst_bud;
  assign line_buf1_rsc_Denoise_inst_d = line_buf1_rsc_d_n_Denoise_inst;
  assign line_buf1_rsc_Denoise_inst_adr = line_buf1_rsc_adr_n_Denoise_inst;
  assign dat_out_rsc_vld = dat_out_rsc_vld_n_EdgeDetect_Filter_inst_bud;
  assign dat_out_rsc_dat = dat_out_rsc_dat_n_EdgeDetect_Filter_inst;
  assign ctrl_edgedect_triosy_lz = ctrl_signal_triosy_lz_n_EdgeDetect_Filter_inst_bud;
  assign line_buf0_rsc_EdgeDetect_Filter_inst_en = line_buf0_rsc_en_n_EdgeDetect_Filter_inst;
  assign line_buf0_rsc_EdgeDetect_Filter_inst_we = line_buf0_rsc_we_n_EdgeDetect_Filter_inst_bud;
  assign line_buf0_rsc_EdgeDetect_Filter_inst_d = line_buf0_rsc_d_n_EdgeDetect_Filter_inst;
  assign line_buf0_rsc_EdgeDetect_Filter_inst_adr = line_buf0_rsc_adr_n_EdgeDetect_Filter_inst;
  assign line_buf1_rsc_EdgeDetect_Filter_inst_en = line_buf1_rsc_en_n_EdgeDetect_Filter_inst;
  assign line_buf1_rsc_EdgeDetect_Filter_inst_we = line_buf1_rsc_we_n_EdgeDetect_Filter_inst_bud;
  assign line_buf1_rsc_EdgeDetect_Filter_inst_d = line_buf1_rsc_d_n_EdgeDetect_Filter_inst;
  assign line_buf1_rsc_EdgeDetect_Filter_inst_adr = line_buf1_rsc_adr_n_EdgeDetect_Filter_inst;
endmodule



