// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2023.1/1033555 Production Release
//  HLS Date:       Mon Feb 13 11:32:25 PST 2023
// 
//  Generated by:   m111061545@ws41
//  Generated date: Sun Feb  4 23:03:18 2024
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    leading_sign_19_0
// ------------------------------------------------------------------


module leading_sign_19_0 (
  mantissa, rtn
);
  input [18:0] mantissa;
  output [4:0] rtn;


  // Interconnect Declarations
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_6_2_sdt_2;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_18_3_sdt_3;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_26_2_sdt_2;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_42_4_sdt_4;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_48_2_sdt_1;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_6_2_sdt_1;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_14_2_sdt_1;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_26_2_sdt_1;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_34_2_sdt_1;
  wire c_h_1_2;
  wire c_h_1_5;
  wire c_h_1_6;
  wire c_h_1_8;

  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_and_nl;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_and_1_nl;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_and_76_nl;
  wire ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_or_1_nl;

  // Interconnect Declarations for Component Instantiations 
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_6_2_sdt_2
      = ~((mantissa[16:15]!=2'b00));
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_6_2_sdt_1
      = ~((mantissa[18:17]!=2'b00));
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_14_2_sdt_1
      = ~((mantissa[14:13]!=2'b00));
  assign c_h_1_2 = ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_6_2_sdt_1
      & ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_6_2_sdt_2;
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_18_3_sdt_3
      = (mantissa[12:11]==2'b00) & ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_14_2_sdt_1;
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_26_2_sdt_2
      = ~((mantissa[8:7]!=2'b00));
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_26_2_sdt_1
      = ~((mantissa[10:9]!=2'b00));
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_34_2_sdt_1
      = ~((mantissa[6:5]!=2'b00));
  assign c_h_1_5 = ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_26_2_sdt_1
      & ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_26_2_sdt_2;
  assign c_h_1_6 = c_h_1_2 & ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_18_3_sdt_3;
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_42_4_sdt_4
      = (mantissa[4:3]==2'b00) & ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_34_2_sdt_1
      & c_h_1_5;
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_48_2_sdt_1
      = ~((mantissa[2:1]!=2'b00));
  assign c_h_1_8 = c_h_1_6 & ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_42_4_sdt_4;
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_and_nl
      = c_h_1_6 & (~ ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_42_4_sdt_4);
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_and_1_nl
      = c_h_1_2 & (c_h_1_5 | (~ ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_18_3_sdt_3))
      & (~ c_h_1_8);
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_and_76_nl
      = ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_6_2_sdt_1
      & (ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_14_2_sdt_1
      | (~ ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_6_2_sdt_2))
      & (~((~(ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_26_2_sdt_1
      & (ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_34_2_sdt_1
      | (~ ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_26_2_sdt_2))))
      & c_h_1_6)) & (ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_48_2_sdt_1
      | (~ c_h_1_8));
  assign ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_or_1_nl
      = ((~((mantissa[18]) | (~((mantissa[17:16]!=2'b01))))) & (~(((mantissa[14])
      | (~((mantissa[13:12]!=2'b01)))) & c_h_1_2)) & (~((~((~((mantissa[10]) | (~((mantissa[9:8]!=2'b01)))))
      & (~(((mantissa[6]) | (~((mantissa[5:4]!=2'b01)))) & c_h_1_5)))) & c_h_1_6))
      & (~((~((mantissa[2:1]==2'b01))) & c_h_1_8))) | ((~ (mantissa[0])) & ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_wrs_c_48_2_sdt_1
      & c_h_1_8);
  assign rtn = {c_h_1_8 , ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_and_nl
      , ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_and_1_nl
      , ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_and_76_nl
      , ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_ac_math_ac_normalize_19_19_false_AC_TRN_AC_WRAP_leading_1_leading_sign_19_0_rtn_or_1_nl};
endmodule



